### ISSUE TITLE
es module version

### ISSUE THREAD

**Issue by daKmoR** [rayrutjes/diffable-html#17]
hey,

diffable-html is not available as an es module version

I would like to do something like this (natively in the browser)
```js
import toDiffableHtml from './node_modules/diffable-html/dist/diffable-html.js';
// solution could be an alternative dist
import toDiffableHtml from './node_modules/diffable-html/dist/diffable-html-esm.js';
```

would you be interested in offering an es module versions then I can prepare a PR. 
(possibly using rollup or even turning it around and have an es module source and export a node/amd package => details could be discussed if this is a possible route)

**Comment by rayrutjes** [comment]
I'm all in to provide an ES module.
I think we can easily add it to the Rollup config.
I've been a bit detached from JS ecosystem for the last months so I'd appreciate a PR :)

**Comment by daKmoR** [comment]
**first** that's awesome to hear :)

**second** I tried to make this happen but it seems I hit a brick wall :(
Apparently, htmlparser2 does not play nicely with rollup... as it's exports are somewhat "[funky](https://github.com/fb55/htmlparser2/blob/master/lib/index.js#L5)" https://github.com/fb55/htmlparser2/issues/223

some more details:
https://github.com/rollup/rollup/issues/1390
https://github.com/rollup/rollup/issues/1674

so I'm not really sure what to do next?
Would you be willing to rewrite or accept a PR with a rewrite to parse5? (I know parse5 works fine as a bundles es module)
or any other ideas?

**Comment by daKmoR** [comment]
Sooo I found a workaround... 🎉 
Some background:
The problem is that htmlparser2 has some really strange requires within it's index.js - I assume to improve performance - however, this also makes it impossible to statically analyze. Which is sort of needed to make it a proper es module.

The workaround is to not load htmlparser2 via index.js.
```
- var htmlparser2 = require('htmlparser2');
+ var htmlparser2Parser = require('htmlparser2/lib/Parser');");

-  var parser = new htmlparser2.Parser(
+ var parser = new htmlparser2Parser(
```

using that rollup can figure out all that is needed.

I want to test this properly first so I made a temporary publishing of it via `@bundled-es-modules`.

You can see the rollup config here: https://github.com/bundled-es-modules/diffable-html/blob/master/rollup.config.js

As you can see this now bundles everything into one file and from my initial tests it seems to work fine.

If these 2 line changes + published as a bundle + changes to the rollup config still look good I can prepare a PR in the upcomming day.

just let me know 🤗

**Comment by rayrutjes** [comment]
I hope to find some time to work on this next week.
I'd also be open to consider any PR you provide.

Sorry about the delay :/

**Comment by daKmoR** [comment]
now worries - also we sort of moved away from parsing dom strings ourself.
As we run our tests in the browser we can just use the dom parser itself - which means 0 dependencies and more performant.

an es module version for `diffable-html` might still be intersting but its primary use would probably be node and as the node es module support is still not as great as it should be I think there is no need to rush (also htmlparser2 is kina not es module compliant which makes it unnecessarily complicated) 

anyway if there are questions I'm happy to answer 🤗 

PS: I will close the issue as it's not a problem for me anymore - feel free to reopen if you want to keep it open for tracking the es module process.
